create table
  public."serviceCentres" (
    id bigint generated by default as identity,
    "createdAt" timestamp with time zone not null default now(),
    name text null,
    identifier text not null,
    "isArchived" boolean null default false,
    "keyStart" bigint null,
    "keyEnd" bigint null,
    localities text[] null,
    constraint service_centres_pkey primary key (id)
  ) tablespace pg_default;
alter table public."serviceCentres" ENABLE ROW LEVEL SECURITY;