create table
  public.milestones (
    id bigint generated by default as identity,
    "createdAt" timestamp with time zone not null default now(),
    identifier text null,
    descriptor text null,
    index integer null,
    interval integer null,
    entities text[] null,
    "legalEntityId" bigint not null,
    constraint milestones_pkey primary key (id),
    constraint milestones_legalEntityId_fkey foreign key ("legalEntityId") references "legalEntities" (id) on delete cascade
  ) tablespace pg_default;