create table
  public.providers (
    id bigint generated by default as identity,
    "createdAt" timestamp with time zone not null default now(),
    name text not null,
    "serviceCentreId" bigint not null,
    "isArchived" boolean null default false,
    "keyStart" bigint null,
    "keyEnd" bigint null,
    localities text[] null,
    constraint providers_pkey primary key (id)
  ) tablespace pg_default;
alter table public.providers ENABLE ROW LEVEL SECURITY;