create table
  public.holidays (
    id bigint generated by default as identity,
    "createdAt" timestamp with time zone not null default now(),
    "entityId" bigint null,
    date date null,
    observed date null,
    name text null,
    entity text null,
    locality text null,
    constraint holiday_pkey primary key (id),
    constraint holidays_locality_fkey foreign key (locality) references localities ("isoCode")
  ) tablespace pg_default;
alter table public.holidays ENABLE ROW LEVEL SECURITY;