create table
  public.holidays (
    id bigint generated by default as identity,
    "createdAt" timestamp with time zone not null default now(),
    locality text not null,
    date date null,
    observed date null,
    name text null,
    entity text null,
    "entityId" bigint null,
    "isRemoved" boolean null,    
    constraint holiday_pkey primary key (id),
    constraint holidays_locality_fkey foreign key (locality) references localities ("isoCode")
  ) tablespace pg_default;
alter table public.holidays ENABLE ROW LEVEL SECURITY;