create table
  public.clients (
    id bigint generated by default as identity,
    "createdAt" timestamp with time zone not null default now(),
    name text not null,
    identifier text not null,
    "isArchived" boolean null default false,
    "parentId" bigint null,
    "keyStart" bigint null,
    "keyEnd" bigint null,
    localities text[] null,
    "serviceCentreId" bigint not null,
    constraint clients_pkey primary key (id),
    constraint clients_parentId_fkey foreign key ("parentId") references clients (id) on delete cascade,
    constraint clients_serviceCentreId_fkey foreign key ("serviceCentreId") references "serviceCentres" (id)
  ) tablespace pg_default;
alter table public.clients ENABLE ROW LEVEL SECURITY;